import { getListOfBreeds } from "./mainData.js"
import { deFaultDogList } from "./defaultDoglis.js"
import { btnRandom } from "./randomBtn.js"
import { displayNumber } from "./displayNumber.js"
import { dateString } from "./date.js"